name: flutter_boost
description: A package for simple and fast flutter development
version: 0.0.1
author: aasirmutwalli22@gmail.com
homepage: https://github.com/aasirmutwalli22/flutter_boost.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: